import 'package:musico/core/key/app_images.dart';
import 'package:musico/core/constant/app_strings.dart';
import 'package:musico/core/key/song_path.dart';

class Song {
  final String songName;
  final String artistName;
  final String artistPhoto;
  final String image;
  final String language;
  final int likes;
  final int totalDownloads;
  final String category;
  final String song;

  Song({
    required this.song,
    required this.songName,
    required this.artistPhoto,
    required this.artistName,
    required this.image,
    required this.language,
    required this.likes,
    required this.totalDownloads,
    required this.category,
  });

  static final List<Song> allSongs = [

    // For You
    Song(
        song: SongPath.song1,
        songName: "Chalte Chalte",
        artistName: "Atif Aslam",
        image: AppImages.song1,
        language: "Hindi",
        likes: 200,
        totalDownloads: 20,
        category: AppStrings.category1,
        artistPhoto: AppImages.artist1), 
    Song(
      song: SongPath.song2,
        songName: "Tum Hi Ho",
        artistName: "Arijit Singh",
        image: AppImages.song2,
        language: "Hindi",
        likes: 350,
        totalDownloads: 50,
        category: AppStrings.category1,
        artistPhoto: AppImages.artist2),
    Song(
      song: SongPath.song3,
        songName: "Raabta",
        artistName: "Arijit Singh",
        image: AppImages.song3,
        language: "Hindi",
        likes: 270,
        totalDownloads: 45,
        category: AppStrings.category1,
        artistPhoto: AppImages.artist3),
    Song(
      song: SongPath.song4,
        songName: "Shape of You",
        artistName: "Ed Sheeran",
        image: AppImages.song4,
        language: "English",
        likes: 1000,
        totalDownloads: 500,
        category: AppStrings.category1,
        artistPhoto: AppImages.artist4),
    Song(
      song: SongPath.song5,
        songName: "Perfect",
        artistName: "Ed Sheeran",
        image: AppImages.song5,
        language: "English",
        likes: 900,
        totalDownloads: 450,
        category: AppStrings.category1,
        artistPhoto: AppImages.artist5),

    // Relax
    Song(
      song: SongPath.song6,
        songName: "River Flows in You",
        artistName: "Yiruma",
        image: AppImages.song6,
        language: "Instrumental",
        likes: 500,
        totalDownloads: 100,
        category: AppStrings.category2,
        artistPhoto: AppImages.artist6),
    Song(
      song: SongPath.song7,
        songName: "Weightless",
        artistName: "Marconi Union",
        image: AppImages.song7,
        language: "Instrumental",
        likes: 400,
        totalDownloads: 80,
        category: AppStrings.category2,
        artistPhoto: AppImages.artist7),
    Song(
      song: SongPath.song1,
        songName: "Someone Like You",
        artistName: "Adele",
        image: AppImages.song8,
        language: "English",
        likes: 600,
        totalDownloads: 150,
        category: AppStrings.category2,
        artistPhoto: AppImages.artist1),
    Song(
      song: SongPath.song2,
        songName: "Photograph",
        artistName: "Ed Sheeran",
        image: AppImages.song9,
        language: "English",
        likes: 450,
        totalDownloads: 120,
        category: AppStrings.category2,
        artistPhoto: AppImages.artist2),
    Song(
      song: SongPath.song3,
        songName: "Fix You",
        artistName: "Coldplay",
        image: AppImages.song10,
        language: "English",
        likes: 700,
        totalDownloads: 200,
        category: AppStrings.category2,
        artistPhoto: AppImages.artist3),

    // Workout
    Song(
      song: SongPath.song4,
        songName: "Stronger",
        artistName: "Kanye West",
        image: AppImages.song11,
        language: "English",
        likes: 600,
        totalDownloads: 200,
        category: AppStrings.category3,
        artistPhoto: AppImages.artist4),
    Song(
      song: SongPath.song5,
        songName: "Lose Yourself",
        artistName: "Eminem",
        image: AppImages.song12,
        language: "English",
        likes: 800,
        totalDownloads: 300,
        category: AppStrings.category3,
        artistPhoto: AppImages.artist5),
    Song(
      song: SongPath.song6,
        songName: "Eye of the Tiger",
        artistName: "Survivor",
        image: AppImages.song1,
        language: "English",
        likes: 500,
        totalDownloads: 220,
        category: AppStrings.category3,
        artistPhoto: AppImages.artist6),
    Song(
      song: SongPath.song7,
        songName: "Till I Collapse",
        artistName: "Eminem",
        image: AppImages.song2,
        language: "English",
        likes: 900,
        totalDownloads: 400,
        category: AppStrings.category3,
        artistPhoto: AppImages.artist7),
    Song(
      song: SongPath.song1,
        songName: "Stronger (What Doesn't Kill You)",
        artistName: "Kelly Clarkson",
        image: AppImages.song3,
        language: "English",
        likes: 750,
        totalDownloads: 310,
        category: AppStrings.category3,
        artistPhoto: AppImages.artist1),

    // Travel
    Song(
      song: SongPath.song2,
        songName: "Kun Faya Kun",
        artistName: "A.R. Rahman",
        image: AppImages.song4,
        language: "Hindi",
        likes: 700,
        totalDownloads: 250,
        category: AppStrings.category4,
        artistPhoto: AppImages.artist2),
    Song(
      song: SongPath.song3,
        songName: "Ilahi",
        artistName: "Arijit Singh",
        image: AppImages.song5,
        language: "Hindi",
        likes: 600,
        totalDownloads: 230,
        category: AppStrings.category4,
        artistPhoto: AppImages.artist3),
    Song(
      song: SongPath.song4,
        songName: "Dil Chahta Hai",
        artistName: "Shankar Ehsaan Loy",
        image: AppImages.song6,
        language: "Hindi",
        likes: 550,
        totalDownloads: 210,
        category: AppStrings.category4,
        artistPhoto: AppImages.artist4),
    Song(
      song: SongPath.song5,
        songName: "On Top of the World",
        artistName: "Imagine Dragons",
        image: AppImages.song7,
        language: "English",
        likes: 500,
        totalDownloads: 180,
        category: AppStrings.category4,
        artistPhoto: AppImages.artist5),
    Song(
      song: SongPath.song6,
        songName: "Castle on the Hill",
        artistName: "Ed Sheeran",
        image: AppImages.song8,
        language: "English",
        likes: 480,
        totalDownloads: 170,
        category: AppStrings.category4,
        artistPhoto: AppImages.artist6),

    // Focus
    Song(
      song: SongPath.song7,
        songName: "Clair de Lune",
        artistName: "Claude Debussy",
        image: AppImages.song9,
        language: "Instrumental",
        likes: 400,
        totalDownloads: 150,
        category: AppStrings.category5,
        artistPhoto: AppImages.artist7),
    Song(
      song: SongPath.song1,
        songName: "Nocturne Op. 9 No. 2",
        artistName: "Chopin",
        image: AppImages.song10,
        language: "Instrumental",
        likes: 350,
        totalDownloads: 130,
        category: AppStrings.category5,
        artistPhoto: AppImages.artist1),
    Song(
      song: SongPath.song2,
        songName: "Weightless",
        artistName: "Marconi Union",
        image: AppImages.song11,
        language: "Instrumental",
        likes: 320,
        totalDownloads: 110,
        category: AppStrings.category5,
        artistPhoto: AppImages.artist2),
    Song(
      song: SongPath.song3,
        songName: "Comptine d'un autre été",
        artistName: "Yann Tiersen",
        image: AppImages.song12,
        language: "Instrumental",
        likes: 500,
        totalDownloads: 180,
        category: AppStrings.category5,
        artistPhoto: AppImages.artist3),
    Song(
      song: SongPath.song4,
        songName: "A Thousand Years",
        artistName: "Christina Perri",
        image: AppImages.song1,
        language: "English",
        likes: 700,
        totalDownloads: 260,
        category: AppStrings.category5,
        artistPhoto: AppImages.artist4),

    // Energize
    Song(
      song: SongPath.song5,
        songName: "Happy",
        artistName: "Pharrell Williams",
        image: AppImages.song2,
        language: "English",
        likes: 900,
        totalDownloads: 400,
        category: AppStrings.category6,
        artistPhoto: AppImages.artist5),
    Song(
      song: SongPath.song6,
        songName: "Can't Stop the Feeling!",
        artistName: "Justin Timberlake",
        image: AppImages.song3,
        language: "English",
        likes: 800,
        totalDownloads: 350,
        category: AppStrings.category6,
        artistPhoto: AppImages.artist6),
    Song(
      song: SongPath.song7,
        songName: "Uptown Funk",
        artistName: "Bruno Mars",
        image: AppImages.song4,
        language: "English",
        likes: 850,
        totalDownloads: 370,
        category: AppStrings.category6,
        artistPhoto: AppImages.artist7),
    Song(
      song: SongPath.song1,
        songName: "Shake It Off",
        artistName: "Taylor Swift",
        image: AppImages.song5,
        language: "English",
        likes: 750,
        totalDownloads: 310,
        category: AppStrings.category6,
        artistPhoto: AppImages.artist1),
    Song(
      song: SongPath.song2,
        songName: "Waka Waka",
        artistName: "Shakira",
        image: AppImages.song6,
        language: "English",
        likes: 1000,
        totalDownloads: 450,
        category: AppStrings.category6,
        artistPhoto: AppImages.artist2),
  ];
}
